name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "Dockerfile"
  schedule:
    - cron: "0 6 * * */3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          cache-from: type=registry,ref=jakeygilly/finderweb:buildcache
          cache-to: type=registry,ref=jakeygilly/finderweb:buildcache,mode=max
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/jakeygilly/finderweb:latest
          cache-from: type=registry,ref=jakeygilly/finderweb:buildcache
          cache-to: type=registry,ref=jakeygilly/finderweb:buildcache,mode=max
